// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client"

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never
  }

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >
}[Exclude<TCustomType[number], string>["id"]]

type HomeDocumentDataSlicesSlice =
  | EventDetailsHighlightSlice
  | TimelineMilestonesSlice
  | EventsSlice
  | FeaturedProfileWithDescriptionSlice
  | HeroSlice

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>

/**
 * Content for Site Settings documents
 */
interface SettingsDocumentData {
  /**
   * SBDC Logo field in *Site Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.sbdc_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  sbdc_logo: prismic.ImageField<never>

  /**
   * Nupura Logo field in *Site Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nupura_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  nupura_logo: prismic.ImageField<never>

  /**
   * Banner Text field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  banner: prismic.KeyTextField

  /**
   * Address field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address: prismic.KeyTextField

  /**
   * Instagram field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  instagram: prismic.KeyTextField

  /**
   * Number field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  number: prismic.KeyTextField
}

/**
 * Site Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >

export type AllDocumentTypes = HomeDocument | SettingsDocument

/**
 * Primary content in *EventHighlight → Default → Primary*
 */
export interface EventDetailsHighlightSliceDefaultPrimary {
  /**
   * Section Heading field in *EventHighlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_details_highlight.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField

  /**
   * Image field in *EventHighlight → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event_details_highlight.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>

  /**
   * Subtitle field in *EventHighlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_details_highlight.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField

  /**
   * Event Title field in *EventHighlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_details_highlight.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * Date field in *EventHighlight → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: event_details_highlight.default.primary.date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField

  /**
   * Venue field in *EventHighlight → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: event_details_highlight.default.primary.venue
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  venue: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * Entry Time field in *EventHighlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_details_highlight.default.primary.entry_time
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  entry_time: prismic.KeyTextField

  /**
   * Show Time field in *EventHighlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_details_highlight.default.primary.show_time
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  show_time: prismic.KeyTextField

  /**
   * CTA Button field in *EventHighlight → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: event_details_highlight.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >
}

/**
 * Default variation for EventHighlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with image on the left and event details (title, subtitle, metadata, CTA) on the right.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventDetailsHighlightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventDetailsHighlightSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *EventHighlight*
 */
type EventDetailsHighlightSliceVariation = EventDetailsHighlightSliceDefault

/**
 * EventHighlight Shared Slice
 *
 * - **API ID**: `event_details_highlight`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventDetailsHighlightSlice = prismic.SharedSlice<
  "event_details_highlight",
  EventDetailsHighlightSliceVariation
>

/**
 * Item in *Events → Default → Primary → Events*
 */
export interface EventsSliceDefaultPrimaryEventsItem {
  /**
   * Date field in *Events → Default → Primary → Events*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.events[].date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField

  /**
   * Name field in *Events → Default → Primary → Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.events[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField

  /**
   * Description field in *Events → Default → Primary → Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.events[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField

  /**
   * Time field in *Events → Default → Primary → Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.events[].time
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  time: prismic.KeyTextField

  /**
   * Registration Link field in *Events → Default → Primary → Events*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.events[].registrationLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  registrationLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >
}

/**
 * Primary content in *Events → Default → Primary*
 */
export interface EventsSliceDefaultPrimary {
  /**
   * Section Heading field in *Events → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField

  /**
   * Venue field in *Events → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.venue
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  venue: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * Events field in *Events → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.events[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  events: prismic.GroupField<Simplify<EventsSliceDefaultPrimaryEventsItem>>
}

/**
 * Default variation for Events Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventsSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Events*
 */
type EventsSliceVariation = EventsSliceDefault

/**
 * Events Shared Slice
 *
 * - **API ID**: `events`
 * - **Description**: Events
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventsSlice = prismic.SharedSlice<"events", EventsSliceVariation>

/**
 * Primary content in *FeaturedProfileWithDescription → Default → Primary*
 */
export interface FeaturedProfileWithDescriptionSliceProfileRightAlignedTextPrimary {
  /**
   * Profile Image field in *FeaturedProfileWithDescription → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile_with_description.profile_right_aligned_text.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>

  /**
   * Title field in *FeaturedProfileWithDescription → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile_with_description.profile_right_aligned_text.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * Description field in *FeaturedProfileWithDescription → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile_with_description.profile_right_aligned_text.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField
}

/**
 * Default variation for FeaturedProfileWithDescription Slice
 *
 * - **API ID**: `profile_right_aligned_text`
 * - **Description**: Displays the profile image on the left and right-aligned text content featuring a heading and detailed description.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedProfileWithDescriptionSliceProfileRightAlignedText =
  prismic.SharedSliceVariation<
    "profile_right_aligned_text",
    Simplify<FeaturedProfileWithDescriptionSliceProfileRightAlignedTextPrimary>,
    never
  >

/**
 * Slice variation for *FeaturedProfileWithDescription*
 */
type FeaturedProfileWithDescriptionSliceVariation =
  FeaturedProfileWithDescriptionSliceProfileRightAlignedText

/**
 * FeaturedProfileWithDescription Shared Slice
 *
 * - **API ID**: `featured_profile_with_description`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedProfileWithDescriptionSlice = prismic.SharedSlice<
  "featured_profile_with_description",
  FeaturedProfileWithDescriptionSliceVariation
>

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Eyebrow Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField

  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField

  /**
   * Ticket Call to Action field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.ticket
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  ticket: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * Workshops Call to Action field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.workshops
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  workshops: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>

/**
 * Item in *Timeline → Default → Primary → Timeline Items*
 */
export interface TimelineMilestonesSliceDefaultPrimaryTimelineItem {
  /**
   * Year field in *Timeline → Default → Primary → Timeline Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_milestones.default.primary.timeline[].year
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  year: prismic.KeyTextField

  /**
   * Image field in *Timeline → Default → Primary → Timeline Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_milestones.default.primary.timeline[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>

  /**
   * Description field in *Timeline → Default → Primary → Timeline Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_milestones.default.primary.timeline[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField
}

/**
 * Primary content in *Timeline → Default → Primary*
 */
export interface TimelineMilestonesSliceDefaultPrimary {
  /**
   * Section Heading field in *Timeline → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_milestones.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField

  /**
   * Timeline Items field in *Timeline → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_milestones.default.primary.timeline[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  timeline: prismic.GroupField<
    Simplify<TimelineMilestonesSliceDefaultPrimaryTimelineItem>
  >
}

/**
 * Default variation for Timeline Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays milestones vertically, each with a year, headline, image, and accompanying description.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TimelineMilestonesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TimelineMilestonesSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Timeline*
 */
type TimelineMilestonesSliceVariation = TimelineMilestonesSliceDefault

/**
 * Timeline Shared Slice
 *
 * - **API ID**: `timeline_milestones`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TimelineMilestonesSlice = prismic.SharedSlice<
  "timeline_milestones",
  TimelineMilestonesSliceVariation
>

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      EventDetailsHighlightSlice,
      EventDetailsHighlightSliceDefaultPrimary,
      EventDetailsHighlightSliceVariation,
      EventDetailsHighlightSliceDefault,
      EventsSlice,
      EventsSliceDefaultPrimaryEventsItem,
      EventsSliceDefaultPrimary,
      EventsSliceVariation,
      EventsSliceDefault,
      FeaturedProfileWithDescriptionSlice,
      FeaturedProfileWithDescriptionSliceProfileRightAlignedTextPrimary,
      FeaturedProfileWithDescriptionSliceVariation,
      FeaturedProfileWithDescriptionSliceProfileRightAlignedText,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      TimelineMilestonesSlice,
      TimelineMilestonesSliceDefaultPrimaryTimelineItem,
      TimelineMilestonesSliceDefaultPrimary,
      TimelineMilestonesSliceVariation,
      TimelineMilestonesSliceDefault,
    }
  }
}
