// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  event_details_highlight: dynamic(() => import("./EventHighlight")),
  events: dynamic(() => import("./Events")),
  featured_profile_with_description: dynamic(
    () => import("./FeaturedProfileWithDescription"),
  ),
  hero: dynamic(() => import("./Hero")),
  timeline_milestones: dynamic(() => import("./Timeline")),
};
